### PR TITLE
117 iterable mapping

### LINKED ISSUE #117: [contracts] LibIterableMapping Tests
**Describe the bug**
The iterable mapping tests have not yet been implemented

### PR DESCRIPTION
**Pull request by LayneHaber**
## The Problem
Fixes #117 

## The Solution
See changelog

### CODE REVIEW

File: modules/contracts/src.ts/tests/lib/iterableMapping.spec.ts [hunk 1]
```diff
@@ -1,50 +1,166 @@
...
-describe("LibIterableMapping.sol", () => {
+import { RegisteredTransfer } from "@connext/vector-types";
+import { expect } from "chai";
+import { BigNumber, Contract } from "ethers";
+
+import { deployContracts } from "../../actions";
+import { alice } from "../constants";
+import { getTestAddressBook } from "../utils";
+
+describe.only("LibIterableMapping.sol", () => {
```
Comment (rhlsthrm) [inline modules/contracts/src.ts/tests/lib/iterableMapping.spec.ts:11]: Remove .only.

**Review by rhlsthrm — CHANGES_REQUESTED** [review]

File: modules/contracts/src.ts/tests/lib/iterableMapping.spec.ts (hunk 1 above)
Comment (HeikoFisch) [reply modules/contracts/src.ts/tests/lib/iterableMapping.spec.ts]: Removed.

**Review by bohendo — APPROVED** [review]
Looks great
