### PR TITLE
547 in memory progress

### LINKED ISSUE #547: [router] Make PROCESSING update status an in-memory flag
**Describe the bug**
Router marks queued updates as `PROCESSING` when handling them in the `isAlive` functions. This is not restart-resistant. If a router is upgraded or restarted while an update is being processed, it will never be resumed properly.

The status is designed to prevent errors when people are hammering the `isAlive` endpoint, and this should be handled in-memory instead.

### PR DESCRIPTION
**Pull request by LayneHaber**
## The Problem

Fixes #547

### CODE REVIEW

**Review by rhlsthrm — APPROVED** [review]

File: modules/router/src/forwarding.ts [hunk 1]
```diff
@@ -1067,10 +1072,12 @@ export const handlePendingUpdates = async (
   }
   const channel = channelRes.getValue() as FullChannelState;
 
+  // This means the user is online and has checked in. Get all updates that are
+  // queued and then execute them.
+  const updates = await store.getQueuedUpdates(data.channelAddress, [RouterUpdateStatus.PENDING]);
```
Comment (rhlsthrm) [inline modules/router/src/forwarding.ts:1076]: try-catch

**Review by rhlsthrm — CHANGES_REQUESTED** [review]
Lgtm pending try catch.

**Review by rhlsthrm — APPROVED** [review]
