### PR TITLE
259 concurrency tests

### LINKED ISSUE #259: [test-runner] Improve concurrency tests
**Describe the bug**
Revisit and give TLC to concurrency tests

### PR DESCRIPTION
**Pull request by LayneHaber**
## The Problem

Fixes #259

### CODE REVIEW

File: modules/test-runner/src/load/helpers/agent.ts [hunk 1]
```diff
@@ -90,11 +97,14 @@ export class Agent {
   ): Promise<Agent> {
     // Create node on server at idx
     // NOTE: can safely be called multiple times
+    console.log("****** trying to create new agent at", index);
     const nodeRes = await nodeService.createNode({ index });
     if (nodeRes.isError) {
+      console.log("****** creating node at", index, "failed");
```
Comment (rhlsthrm) [inline modules/test-runner/src/load/helpers/agent.ts:103]: Do we need these logs?

**Review by rhlsthrm — APPROVED** [review]
